service: gender-pay-gap-bot-2
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
  region: eu-west-2
package:
  include:
    - ./dist/**
    - node_modules/**
    - data/companies_GPG_Data.json
  exclude:
    - ./**

functions:
  getCompany:
    handler: dist/api/getCompanyHandler.getCompany
    events:
     - httpApi:
         path: /company/{id}
         method: get
