service: gender-pay-gap-bot-2
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
  region: eu-west-2
package:
  include:
    - ./dist/**
    - data/companyDataJoinedWithTweets.json
    - data/twitterAccountData/twitterUserData-prod.json
    - data/twitterAccountData/twitterUserData-test.json
    - data/companies_GPG_Data.json
    - node_modules/**

  exclude:
    - ./**

functions:
  getCompanyByCompanyId:
    handler: dist/api/getCompanyHandler.getCompanyByCompanyId
    events:
     - httpApi:
         path: /company/{id}
         method: get

  getCompanyByTwitterId:
    handler: dist/api/getCompanyHandler.getCompanyByTwitterId
    events:
     - httpApi:
         path: /company/twitterId/{id}
         method: get

  getCompanyByTwitterHandle:
    handler: dist/api/getCompanyHandler.getCompanyByTwitterHandle
    events:
     - httpApi:
         path: /company/twitterHandle/{handle}
         method: get

  tweetGpg:
    handler: dist/tweetGPG/handler.handler
    role: TweetSqsProcessorRole
    environment:
      TWITTER_API_KEY: ${env:TWITTER_API_KEY}
      TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}
      TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
      TWITTER_BEARER_TOKEN: ${env:TWITTER_BEARER_TOKEN}
      TWITTER_USER_ID: ${env:TWITTER_USER_ID}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TweetQueue
              - Arn
          batchSize: 1
          maximumBatchingWindow: 60

resources:
  Resources:
    # SQS for queuing tweets.
    TweetQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TweetQueue"
        MessageRetentionPeriod: 1209600 # 14 days retention.
        RedrivePolicy:
          deadLetterTargetArn: 
            Fn::GetAtt: [ TweetQueueDeadLetter, Arn ]
          maxReceiveCount: 3
    # Dead letter queue for the above.
    TweetQueueDeadLetter:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TweetQueueDeadLetter"
        MessageRetentionPeriod: 1209600 # 14 days retention.

    # EC2 for Tweet listener and queuer
    # Docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    TweetListenerQueuer:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-0dd555eb7eb3b7c82 # Linux 2
        KeyName: GenderPayGapApp
        InstanceType: t2.nano
        SubnetId: subnet-7e54ad32
        SecurityGroupIds:
          - sg-88aeb6e5
        IamInstanceProfile: 
          Ref: ListenerEC2Profile
        # TODO this
        # UserData:
        # 'Fn::Base64': !Sub |
        #   #!/bin/bash -x
            # echo "Running boot up sequence!"
            # cd gender-pay-gap-bot
            # git pull
            # aws s3 cp s3://alifensome-general-bucket/gpga/.env .env
            # npm run start:listener test >> ~/appLogs/logs.txt

    # Profile
    ListenerEC2Profile:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        InstanceProfileName: ListenerEC2Profile
        Roles: 
          - Ref: ListenerRole          

    # Roles
    # https://www.serverless.com/framework/docs/providers/aws/guide/iam
    ListenerRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ListenerRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ListenerRolePolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/ec2/*:*:*'
                    - "arn:aws:logs:eu-west-2:402504474878:log-group:/var/log/*:*:*"
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - 
                      Fn::GetAtt: [ TweetQueue, Arn ]

                - Effect: Allow
                  Action:
                    - s3:GetObject
                  Resource:
                    - arn:aws:s3:::alifensome-general-bucket/gpga/.env

    TweetSqsProcessorRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: TweetSqsProcessorRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: TweetSqsProcessorRolePolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes

                  Resource:
                    - 
                      Fn::GetAtt: [ TweetQueue, Arn ]
