service: gender-pay-gap-bot-2
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
  region: eu-west-2
package:
  include:
    - ./dist/**
    - data/companyDataJoinedWithTweets.json
  exclude:
    - ./**
    - node_modules/**

functions:
  getCompanyByCompanyId:
    handler: dist/api/getCompanyHandler.getCompanyByCompanyId
    events:
     - httpApi:
         path: /company/{id}
         method: get

  getCompanyByTwitterId:
    handler: dist/api/getCompanyHandler.getCompanyByTwitterId
    events:
     - httpApi:
         path: /company/twitterId/{id}
         method: get

  getCompanyByTwitterHandle:
    handler: dist/api/getCompanyHandler.getCompanyByTwitterHandle
    events:
     - httpApi:
         path: /company/twitterHandle/{handle}
         method: get
