const ukCities = [
    "",
    "UK",
    "UNITED KINGDOM",
    "England",
    "Britain",
    "ABERDEEN",
    "ALDERSHOT",
    "ALTRINCHAM",
    "ASHFORD",
    "ATHERTON",
    "AYLESBURY",
    "BAMBER BRIDGE",
    "BANGOR",
    "BARNSLEY",
    "BARRY",
    "BASILDON",
    "BASINGSTOKE",
    "BATH",
    "BATLEY",
    "BEBINGTON",
    "BEDFORD",
    "BEESTON",
    "BELFAST",
    "BIRKENHEAD",
    "BIRMINGHAM",
    "BLACKBURN",
    "BLACKPOOL",
    "BLOXWICH",
    "BOGNOR REGIS",
    "BOLTON",
    "BOOTLE",
    "BOURNEMOUTH",
    "BRACKNELL",
    "BRADFORD",
    "BRENTWOOD",
    "BRIGHTON AND HOVE",
    "BRISTOL",
    "BURNLEY",
    "BURTON UPON TRENT",
    "BURY",
    "CAMBRIDGE",
    "MILTON",
    "CANNOCK",
    "CANTERBURY",
    "CARDIFF",
    "CARLISLE",
    "CARLTON",
    "CHATHAM",
    "CHELMSFORD",
    "CHELTENHAM",
    "CHESTER",
    "CHESTERFIELD",
    "CHRISTCHURCH",
    "CLACTON-ON-SEA",
    "COLCHESTER",
    "CORBY",
    "COVENTRY",
    "CRAWLEY",
    "CREWE",
    "CROSBY",
    "CUMBERNAULD",
    "DARLINGTON",
    "DERBY",
    "DEWSBURY",
    "DONCASTER",
    "DUDLEY",
    "DUNDEE",
    "DUNFERMLINE",
    "DURHAM",
    "EASTBOURNE",
    "EAST KILBRIDE",
    "EASTLEIGH",
    "EDINBURGH",
    "ELLESMERE PORT",
    "ESHER",
    "EWELL",
    "EXETER",
    "FARNBOROUGH",
    "FILTON",
    "FOLKESTONE",
    "GATESHEAD",
    "GILLINGHAM",
    "GLASGOW",
    "GLOUCESTER",
    "GOSPORT",
    "GRAVESEND",
    "GRAYS",
    "GRIMSBY",
    "GUILDFORD",
    "HALESOWEN",
    "HALIFAX",
    "HAMILTON",
    "HARLOW",
    "HARROGATE",
    "HARTLEPOOL",
    "HASTINGS",
    "HEMEL HEMPSTEAD",
    "HEREFORD",
    "HIGH WYCOMBE",
    "HORSHAM",
    "HUDDERSFIELD",
    "IPSWICH",
    "KEIGHLEY",
    "KETTERING",
    "KIDDERMINSTER",
    "HULL",
    "KINGSWINFORD",
    "KIRKCALDY",
    "LANCASTER",
    "LEEDS",
    "LEICESTER",
    "LINCOLN",
    "LITTLEHAMPTON",
    "LIVERPOOL",
    "LIVINGSTON",
    "LONDON",
    "LOUGHBOROUGH",
    "LOWESTOFT",
    "LUTON",
    "MACCLESFIELD",
    "MAIDENHEAD",
    "MAIDSTONE",
    "MANCHESTER",
    "MANSFIELD",
    "MARGATE",
    "MIDDLESBROUGH",
    "MILTON KEYNES",
    "NEATH",
    "NEWCASTLE",
    "NEWCASTLE-UNDER-LYME",
    "NEWPORT",
    "NEWTOWNABBEY",
    "NORTHAMPTON",
    "NORWICH",
    "NOTTINGHAM",
    "NUNEATON",
    "OLDHAM",
    "OXFORD",
    "PAIGNTON",
    "PAISLEY",
    "PETERBOROUGH",
    "PLYMOUTH",
    "POOLE",
    "PORTSMOUTH",
    "PRESTON",
    "RAYLEIGH",
    "READING",
    "REDDITCH",
    "ROCHDALE",
    "ROCHESTER",
    "ROTHERHAM",
    "ROYAL LEAMINGTON SPA",
    "ROYAL TUNBRIDGE WELLS",
    "RUGBY",
    "RUNCORN",
    "SALE",
    "SALFORD",
    "SCARBOROUGH",
    "SCUNTHORPE",
    "SHEFFIELD",
    "SHOREHAM-BY-SEA",
    "SHREWSBURY",
    "SITTINGBOURNE",
    "SLOUGH",
    "SMETHWICK",
    "SOLIHULL",
    "SOUTHAMPTON",
    "SOUTHEND-ON-SEA",
    "SOUTHPORT",
    "SOUTH SHIELDS",
    "STAFFORD",
    "ST ALBANS",
    "STEVENAGE",
    "ST HELENS",
    "STOCKPORT",
    "STOCKTON-ON-TEES",
    "STOKE-ON-TRENT",
    "STOURBRIDGE",
    "SUNDERLAND",
    "SUTTON COLDFIELD",
    "SWANSEA",
    "SWINDON",
    "TAMWORTH",
    "TAUNTON",
    "TELFORD",
    "TORQUAY",
    "TYNEMOUTH",
    "WAKEFIELD",
    "WARRINGTON",
    "WASHINGTON",
    "WATFORD",
    "WELLINGBOROUGH",
    "WELWYN GARDEN CITY",
    "WEST BROMWICH",
    "WESTON-SUPER-MARE",
    "WEYMOUTH",
    "WIDNES",
    "WIGAN",
    "WILLENHALL",
    "WOKING",
    "WOLVERHAMPTON",
    "WORCESTER",
    "WORTHING",
    "WREXHAM",
    "YORk"
]

function isUkLocation(place: string) {
    const location = place.toLocaleUpperCase();
    if (location.includes("USA")) {
        return false
    }

    for (let index = 0; index < ukCities.length; index++) {
        const city = ukCities[index];
        if (location.includes(city)) {
            return true
        }
    }
    return false
}

export { isUkLocation }