export const relevantWords = [
  { phrase: "IWD2023", requiresExact: false },
  { phrase: "IWD23", requiresExact: false },
  { phrase: "WOMENS RIGHTS", requiresExact: false },
  { phrase: "GENDER", requiresExact: true },
  { phrase: "EMBRACEEQUITY", requiresExact: false },
  { phrase: "IWD2022", requiresExact: false },
  { phrase: "IWD2022", requiresExact: false },
  { phrase: "IWD22", requiresExact: false },
  { phrase: "IWD", requiresExact: true },
  { phrase: "INTERNATIONALWOMENSDAY", requiresExact: false },
  { phrase: "CHOOSETOCHALLENGE", requiresExact: false },
  { phrase: "INTERNATIONAL WOMENS DAY", requiresExact: false },
  { phrase: "INTERNATIONAL WOMENS MONTH", requiresExact: false },
  { phrase: "WOMENSDAY", requiresExact: false },
  { phrase: "WOMENS DAY", requiresExact: false },
  { phrase: "BREAKTHEBIAS", requiresExact: false },
  { phrase: "WOMENS HISTORY MONTH", requiresExact: false },
  { phrase: "WOMANS HISTORY MONTH", requiresExact: false },
  { phrase: "WOMENS MONTH", requiresExact: false },
  { phrase: "WOMANS MONTH", requiresExact: false },
  { phrase: "WOMENS WEEK", requiresExact: false },
  { phrase: "GENDER PAY GAP", requiresExact: false },
  { phrase: "PAYGAP", requiresExact: false },
  { phrase: "PAY GAP", requiresExact: false },
  { phrase: "GIRL BOSS", requiresExact: false },
  { phrase: "GIRLBOSS", requiresExact: false },
  { phrase: "EQUALITY", requiresExact: true },
  { phrase: "INTERNATIONALMENSDAY", requiresExact: false },
  { phrase: "IMD", requiresExact: true },
  { phrase: "MENSDAY", requiresExact: false },
  { phrase: "EMPOWER WOMEN", requiresExact: false },
  { phrase: "EMPOWERING WOMEN", requiresExact: false },
  { phrase: "INSPIRATIONAL WOMEN", requiresExact: false },
  { phrase: "CELEBRATE WOMEN", requiresExact: false },
  { phrase: "CELEBRATING WOMEN", requiresExact: false },
];
